repos:

# basic housekeeping hooks (trailing spaces, EOF fixer, yaml check, big files)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

# Ruff: linter + formatter
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.3
  hooks:
    - id: ruff-check
      # run auto-fixes where possible
      args: ["--select", "I,RUF022", "--fix"]
    - id: ruff-format

# mypy
- repo: local
  hooks:
    - id: mypy
      name: mypy (local)
      entry: scripts/run-mypy
      language: python
      # Use the Python version you target in CI/dev
      language_version: python3.9
      # Install mypy into the hook environment.
      additional_dependencies: ["mypy==1.17.0"]
      types: [python]
      require_serial: true
      # pre-commit normally passes filenames; our script ignores them,
      # so disable passing filenames to avoid accidental behavior:
      pass_filenames: false
      verbose: true
