# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv (reads pyproject.toml) and set Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          # enable caching to speed subsequent runs (optional)
          enable-cache: true

      - name: Sync dependencies (includes dev dependencies)
        run: |
          # create and populate a venv according to pyproject/uv.lock
          uv sync --frozen

      - name: Install package into environment (editable)
        run: |
          # install project so tests can import it
          uv pip install -e .

      - name: Lint with ruff
        run: |
          # run ruff from the uv environment (fails the job on lint errors)
          uv run --frozen ruff check .

      - name: Run tests with pytest
        run: |
          uv run --frozen pytest -q
